#2 - WIP
HF6-PROJECT/api pull request #3
Opened 2023-09-26 16:46 UTC by frederikpyt

## Description

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-09-28 10:09 UTC, kristianbinau requested changes

2023-09-28 10:09 UTC, kristianbinau commented on .env.example
> +REDIS_URL="rediss://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"
Can you please just change `REDIS_HOST` to `localhost` & this to `redis` instead of `rediss`

2023-09-28 10:09 UTC, kristianbinau commented on .env.example
> +BLOB_READ_WRITE_TOKEN=""
Write Docs how to setup shiii

2023-09-28 10:09 UTC, kristianbinau commented on prisma/schema.prisma
> +    name     String @db.VarChar(50)
Longer

2023-09-28 10:09 UTC, kristianbinau commented on src/modules/item/blob.service.ts
> +		});
Leave some good small comments explaining stuff

2023-09-28 10:09 UTC, kristianbinau commented on src/modules/item/blob.service.ts
> +		});
And maybe prettier Typescript

2023-09-28 10:09 UTC, kristianbinau commented on .env.example
> +BLOB_READ_WRITE_TOKEN=""
```suggestion
BLOB_READ_WRITE_TOKEN="vercel_blob_rw_0511953119b0c1167283c7453a088727" # Fake vercel token
```

2023-09-28 10:09 UTC, kristianbinau commented on src/modules/item/item.schema.ts
> +});
Implement the Anders way!

2023-09-28 11:03 UTC, frederikpyt commented on src/modules/item/item.schema.ts
> +});
😭

2023-09-28 11:28 UTC, frederikpyt commented on src/modules/item/blob.service.ts
> +		});
Better?
![image](https://github.com/HF6-PROJECT/api/assets/54995208/9d5aba25-51ec-418b-a8d7-ee5a19d55f4d)

2023-09-28 16:00 UTC, kristianbinau approved these changes
🪨

2023-09-28 16:01 UTC, kristianbinau requested changes
Failing tests

2023-09-29 07:59 UTC, kristianbinau approved these changes
🚀

2023-09-29 08:00 UTC, merged